[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [string]$BaseUrl = "http://localhost:5088",
    [string]$PalworldPath,
    [switch]$WriteToSourceMod,
    [switch]$KeepNativeHudDisabled
)

$ErrorActionPreference = "Stop"
. (Join-Path $PSScriptRoot "PalLLM.Tooling.ps1")

function Add-OrderedUniqueString {
    param(
        [Parameter(Mandatory = $true)]
        [System.Collections.Generic.List[string]]$List,

        [string]$Value
    )

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return
    }

    $trimmed = $Value.Trim()
    if (-not $List.Contains($trimmed)) {
        $List.Add($trimmed)
    }
}

function ConvertTo-LuaStringLiteral {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Value
    )

    return '"' + ($Value.Replace('\', '\\').Replace('"', '\"')) + '"'
}

function Resolve-TargetModRoot {
    param(
        [string]$PalworldPath,
        [switch]$WriteToSourceMod
    )

    $sourceModRoot = Get-PalLlmModSourcePath
    if ($WriteToSourceMod) {
        return [pscustomobject]@{
            Scope = "repo_source_mod"
            ModRoot = $sourceModRoot
            Note = "Forced source-mod target."
        }
    }

    $install = $null
    if ($PSBoundParameters.ContainsKey("PalworldPath")) {
        $install = Resolve-PalworldInstall -PalworldPath $PalworldPath
    }
    else {
        try {
            $install = Resolve-PalworldInstall
        }
        catch {
            $install = $null
        }
    }

    if ($install -and (Test-Path -LiteralPath $install.InstalledModPath)) {
        return [pscustomobject]@{
            Scope = "installed_mod"
            ModRoot = $install.InstalledModPath
            Note = "Writing into the installed PalLLM mod."
        }
    }

    $note = if ($install) {
        "Installed PalLLM mod was not found under $($install.ModRoot); writing to the repo source mod instead."
    }
    else {
        "Palworld install was not detected; writing to the repo source mod instead."
    }

    return [pscustomobject]@{
        Scope = "repo_source_mod"
        ModRoot = $sourceModRoot
        Note = $note
    }
}

$bridgeProof = Invoke-PalLlmApi -Method GET -BaseUrl $BaseUrl -Path "/api/bridge/proof"
if ($null -eq $bridgeProof -or $null -eq $bridgeProof.NativeReadiness) {
    throw "Bridge proof did not return a NativeReadiness payload. Start the PalLLM sidecar and try again."
}

$nativeReadiness = $bridgeProof.NativeReadiness
$recommendation = $nativeReadiness.HudBindRecommendation
if ($null -eq $recommendation) {
    throw "Bridge proof did not include HudBindRecommendation."
}

$orderedTargets = [System.Collections.Generic.List[string]]::new()
Add-OrderedUniqueString -List $orderedTargets -Value ([string]$recommendation.RecommendedFullName)
Add-OrderedUniqueString -List $orderedTargets -Value ([string]$recommendation.RecommendedTarget)

foreach ($value in @($recommendation.ConfiguredTargets)) {
    Add-OrderedUniqueString -List $orderedTargets -Value ([string]$value)
}

foreach ($value in @($recommendation.SuggestedConfigTargets)) {
    Add-OrderedUniqueString -List $orderedTargets -Value ([string]$value)
}

if ($orderedTargets.Count -eq 0) {
    $status = [string]$recommendation.Status
    throw "No HUD widget target is ready to apply yet (status=$status). Capture ui_probe evidence in Palworld and re-run the recommendation flow."
}

$target = Resolve-TargetModRoot -PalworldPath $PalworldPath -WriteToSourceMod:$WriteToSourceMod
$configDir = Join-Path $target.ModRoot "config"
$configPath = Join-Path $configDir "native-hud.lua"
$nativeHudEnabled = -not $KeepNativeHudDisabled
$generatedAtUtc = [DateTimeOffset]::UtcNow.ToString("u")

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("-- PalLLM native HUD override")
$lines.Add("-- Generated by scripts/apply-hud-bind-recommendation.ps1 on $generatedAtUtc.")
$lines.Add("-- Source recommendation: $([string]$recommendation.Status)")
$lines.Add("return {")
$lines.Add(("    native_hud_render_enabled = {0}," -f ($(if ($nativeHudEnabled) { "true" } else { "false" }))))
$lines.Add("    native_hud_widget_targets = {")
foreach ($value in $orderedTargets) {
    $lines.Add(("        {0}," -f (ConvertTo-LuaStringLiteral -Value $value)))
}
$lines.Add("    },")
$lines.Add("}")
$fileContent = $lines -join "`r`n"

if ($PSCmdlet.ShouldProcess($configPath, "Write PalLLM native HUD override")) {
    New-Item -ItemType Directory -Force -Path $configDir | Out-Null
    Set-Content -LiteralPath $configPath -Value $fileContent -Encoding ASCII
}

[pscustomobject]@{
    Status = "written"
    BridgeProofStatus = [string]$bridgeProof.Status
    RecommendationStatus = [string]$recommendation.Status
    RecommendedTarget = [string]$recommendation.RecommendedTarget
    NativeHudEnabled = $nativeHudEnabled
    TargetScope = [string]$target.Scope
    ConfigPath = $configPath
    PreferredBridgeConfigPath = [string]$nativeReadiness.NativeHudConfigPath
    BridgeConfigSource = [string]$nativeReadiness.NativeHudConfigSource
    AppliedTargets = $orderedTargets.ToArray()
    Note = [string]$target.Note
}
